[package]
name = "actix-web-rest-api-with-jwt"
version = "0.1.0"
authors = ["SakaDream <bahaimt@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0.8"
actix-rt = "0.2.5"
actix-service = "0.4.2"
log = "0.4.8"
env_logger = "0.7.1"
diesel_migrations = "1.4.0"
serde = "1.0.102"
serde_derive = "1.0.102"
serde_json = "1.0.41"
dotenv = "0.15.0"
futures = "0.1.29"
failure = "0.1.6"
derive_more = "0.15.0"
jsonwebtoken = "6.0.1"
bcrypt = "0.6.1"
time = "0.1.42"

[dependencies.diesel]
version = "1.4.3"
features = ["postgres", "r2d2", "chrono"]

[dependencies.chrono]
version = "0.4.9"
features = ["serde"]

[dependencies.uuid]
version = "0.8.1"
features = ["v4"]
